version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasir-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - kasir-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=kasir
      - DB_USERNAME=kasir_user
      - DB_PASSWORD=kasir_password

  db:
    image: mysql:8.0
    container_name: kasir-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kasir
      MYSQL_USER: kasir_user
      MYSQL_PASSWORD: kasir_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    networks:
      - kasir-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kasir-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: kasir_user
      PMA_PASSWORD: kasir_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - kasir-network

volumes:
  db_data:

networks:
  kasir-network:
    driver: bridge